# Generated by Django 3.2.2 on 2022-10-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isFoodAndDrinkBoss',
        ),
    ]
