# Generated by Django 3.2.2 on 2022-11-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_worker_area_evaluacion'),
        ('users', '0003_remove_user_isfoodanddrinkboss'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='worker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='workers.worker'),
        ),
    ]
