# Generated by Django 3.2.2 on 2022-09-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation_in_area', '0001_initial'),
        ('workers', '0006_alter_worker_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='area_evaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluation_in_area.evaluationarea'),
        ),
    ]
